task - spam mail classification
107123119 S.Sadhana

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [ ]:
pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
spambase = fetch_ucirepo(id=94)

# data (as pandas dataframes)
X = spambase.data.features
y = spambase.data.targets

# metadata
print(spambase.metadata)

# variable information
print(spambase.variables)


{'uci_id': 94, 'name': 'Spambase', 'repository_url': 'https://archive.ics.uci.edu/dataset/94/spambase', 'data_url': 'https://archive.ics.uci.edu/static/public/94/data.csv', 'abstract': 'Classifying Email as Spam or Non-Spam', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 4601, 'num_features': 57, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1999, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C53G6X', 'creators': ['Mark Hopkins', 'Erik Reeber', 'George Forman', 'Jaap Suermondt'], 'intro_paper': None, 'additional_info': {'summary': 'The "spam" concept is diverse: advertisements for products/web sites, make money fast schemes, chain letters, pornography...\n\nThe classification task for this dataset is to determine whether a given email is spam or not.\n\t\nOur collecti

In [ ]:
features = X
target = y
scaler = StandardScaler()
scaler.fit(features)
standardized_data = scaler.transform(features)
features = standardized_data
target = y
X_train, X_test, Y_train, Y_test = train_test_split(features,target, test_size = 0.2, random_state=2)

print(features.shape, X_train.shape, X_test.shape)

(4601, 57) (3680, 57) (921, 57)


CODE USING LIBRARY

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [ ]:
# LOGISTIC REGRESSISON - LIB

spam_detection_lr_lib = LogisticRegression()
spam_detection_lr_lib.fit(X_train, Y_train)
X_test_predicted = spam_detection_lr_lib.predict(X_test)
X_train_predicted = spam_detection_lr_lib.predict(X_train)

#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_predicted)
print(cf_matrix)

# F1 score
f1_score_train = f1_score(Y_train, X_train_predicted)
print('Train data F1 Score =', f1_score_train)
f1_score_test = recall_score(Y_test, X_test_predicted)
print('Test data F1 Score =', f1_score_test)

# recall
recall_train = recall_score(Y_train, X_train_predicted)
print('Train data Recall =', recall_train)
recall_test = recall_score(Y_test, X_test_predicted)
print('Test data Recall =', recall_test)

# precision
precision_train = precision_score(Y_train, X_train_predicted)
print('Train data Precision =', precision_train)
precision_test = precision_score(Y_test, X_test_predicted)
print('Test data Precision =', precision_test)

# accuracy
X_train_predicted = spam_detection_lr_lib.predict(X_train)
train_data_accuracy = accuracy_score(Y_train, X_train_predicted)
print(train_data_accuracy)
print('Accuracy on Train data : ', round(train_data_accuracy*100, 2), '%')

X_test_predicted = spam_detection_lr_lib.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_predicted)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[527  18]
 [ 49 327]]
Train data F1 Score = 0.9112133003183588
Test data F1 Score = 0.8696808510638298
Train data Recall = 0.8963117606123869
Test data Recall = 0.8696808510638298
Train data Precision = 0.9266187050359712
Test data Precision = 0.9478260869565217
0.9317934782608696
Accuracy on Train data :  93.18 %
0.9272529858849077
Accuracy on Test data :  92.73 %


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# SVM - LIB

spam_detection_svm_lib = SVC(kernel='linear')
spam_detection_svm_lib.fit(X_train, Y_train)
X_test_prediction = spam_detection_svm_lib.predict(X_test)
X_train_prediction = spam_detection_svm_lib.predict(X_train)

#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_predicted)
print(cf_matrix)

# F1 score
f1_score_train = f1_score(Y_train, X_train_predicted)
print('Train data F1 Score =', f1_score_train)
f1_score_test = recall_score(Y_test, X_test_predicted)
print('Test data F1 Score =', f1_score_test)

# recall
recall_train = recall_score(Y_train, X_train_predicted)
print('Train data Recall =', recall_train)
recall_test = recall_score(Y_test, X_test_predicted)
print('Test data Recall =', recall_test)

# precision
precision_train = precision_score(Y_train, X_train_predicted)
print('Train data Precision =', precision_train)
precision_test = precision_score(Y_test, X_test_predicted)
print('Test data Precision =', precision_test)

# accuracy
X_train_predicted = spam_detection_svm_lib.predict(X_train)
train_data_accuracy = accuracy_score(Y_train, X_train_predicted)
print(train_data_accuracy)
print('Accuracy on Train data : ', round(train_data_accuracy*100, 2), '%')
X_test_predicted = spam_detection_svm_lib.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_predicted)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[527  18]
 [ 49 327]]
Train data F1 Score = 0.9112133003183588
Test data F1 Score = 0.8696808510638298
Train data Recall = 0.8963117606123869
Test data Recall = 0.8696808510638298
Train data Precision = 0.9266187050359712
Test data Precision = 0.9478260869565217
0.935054347826087
Accuracy on Train data :  93.51 %
0.9283387622149837
Accuracy on Test data :  92.83 %


In [ ]:
# NAIVE BAYES - LIB

spam_detection_nb_lib= GaussianNB()
spam_detection_nb_lib.fit(X_train, Y_train)
X_test_predicted = spam_detection_nb_lib.predict(X_test)
X_train_predicted = spam_detection_nb_lib.predict(X_train)

#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_predicted)
print(cf_matrix)

# F1 score
f1_score_train = f1_score(Y_train, X_train_predicted)
print('Train data F1 Score =', f1_score_train)
f1_score_test = recall_score(Y_test, X_test_predicted)
print('Test data F1 Score =', f1_score_test)

# recall
recall_train = recall_score(Y_train, X_train_predicted)
print('Train data Recall =', recall_train)
recall_test = recall_score(Y_test, X_test_predicted)
print('Test data Recall =', recall_test)

# precision
precision_train = precision_score(Y_train, X_train_predicted)
print('Train data Precision =', precision_train)
precision_test = precision_score(Y_test, X_test_predicted)
print('Test data Precision =', precision_test)

# accuracy
X_train_prediction = spam_detection_nb_lib.predict(X_train)
train_data_accuracy = accuracy_score(Y_train, X_train_predicted)
print(train_data_accuracy)
print('Accuracy on Training data : ', round(train_data_accuracy*100, 2), '%')

# accuracy on test data
X_test_predicted = spam_detection_nb_lib.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_predicted)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[404 141]
 [ 16 360]]
Train data F1 Score = 0.7959302325581397
Test data F1 Score = 0.9574468085106383
Train data Recall = 0.9526791927627001
Test data Recall = 0.9574468085106383
Train data Precision = 0.6834747878182726
Test data Precision = 0.718562874251497
0.8092391304347826
Accuracy on Training data :  92.26 %
0.8295331161780674
Accuracy on Test data :  82.95 %


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


* SVM model has more accuracy and is best compared to other models

CODE FROM SCRATCH

In [ ]:
# LOGISTIC REGRESSION
class Logistic_Regression():
  def __init__(self, learning_rate, no_of_iterations):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  def fit(self, X, Y):
    self.m, self.n = X.shape
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y.values.ravel()

    for i in range(self.no_of_iterations):
      self.update_weights()
  def update_weights(self):

    Y_hat = 1 / (1 + np.exp( - (self.X.dot(self.w) + self.b ) ))

    dw = (1/self.m)*np.dot(self.X.T, (Y_hat - self.Y))
    db = (1/self.m)*np.sum(Y_hat - self.Y)

    self.w = self.w - self.learning_rate * dw
    self.b = self.b - self.learning_rate * db

  def predict(self, X):
    Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b ) ))
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred


In [ ]:
# LOGISTIC REGRESSION
spam_detection_lr = Logistic_Regression(learning_rate=0.02, no_of_iterations=2500)
spam_detection_lr.fit(X_train, Y_train)
X_test_prediction = spam_detection_lr.predict(X_test)
X_train_prediction = spam_detection_lr.predict(X_train)


In [ ]:
# LOGISTIC REGRESSION
#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_prediction)
print(cf_matrix)

# F1 score
f1_score_train = f1_score(Y_train, X_train_prediction)
print('Training data F1 Score =', f1_score_train)
f1_score_test = recall_score(Y_test, X_test_prediction)
print('Test data F1 Score =', f1_score_test)

# recall
recall_train = recall_score(Y_train, X_train_prediction)
print('Training data Recall =', recall_train)
recall_test = recall_score(Y_test, X_test_prediction)
print('Test data Recall =', recall_test)

# precision
precision_train = precision_score(Y_train, X_train_prediction)
print('Training data Precision =', precision_train)
precision_test = precision_score(Y_test, X_test_prediction)
print('Test data Precision =', precision_test)

# accuracy
X_train_prediction = spam_detection_lr.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(training_data_accuracy)
print('Accuracy on Training data : ', round(training_data_accuracy*100, 2), '%')

X_test_prediction = spam_detection_lr.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[526  19]
 [ 57 319]]
Training data F1 Score = 0.8994293865905849
Test data F1 Score = 0.848404255319149
Training data Recall = 0.8775226165622826
Test data Recall = 0.848404255319149
Training data Precision = 0.922457937088515
Test data Precision = 0.9437869822485208
0.9233695652173913
Accuracy on Training data :  92.34 %
0.9174809989142236
Accuracy on Test data :  91.75 %


In [ ]:
# SVM
class SVM_classifier():

  def __init__(self, learning_rate, no_of_iterations, lambda_parameter):
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations
    self.lambda_parameter = lambda_parameter

  def fit(self, X, Y):
    self.m, self.n = X.shape
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y
    for i in range(self.no_of_iterations):
      self.update_weights()

  def update_weights(self):
   y_label = np.where(self.Y <= 0, -1, 1)

   for index, x_i in enumerate(self.X):
      condition = y_label[index] * (np.dot(x_i, self.w) - self.b) >= 1

      if (condition == True):
        dw = 2 * self.lambda_parameter * self.w
        db = 0
      else:
        dw = 2 * self.lambda_parameter * self.w - x_i * y_label[index]
        db = y_label[index]

      self.w = self.w - self.learning_rate * dw
      self.b = self.b - self.learning_rate * db

  def predict(self, X):

    output = np.dot(X, self.w) - self.b
    predicted_labels = np.sign(output)
    y_hat = np.where(predicted_labels <= -1, 0, 1)
    return y_hat

In [ ]:
#SVM
spam_detection_svm = SVM_classifier(learning_rate=0.002, no_of_iterations=2500, lambda_parameter=0.01)
spam_detection_svm.fit(X_train, Y_train)
X_test_prediction = spam_detection_svm.predict(X_test)
X_train_prediction = spam_detection_svm.predict(X_train)

In [ ]:
#SVM

#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_prediction)
print(cf_matrix)

# F1 score
f1_score_train = f1_score(Y_train, X_train_prediction)
print('Training data F1 Score =', f1_score_train)
f1_score_test = recall_score(Y_test, X_test_prediction)
print('Test data F1 Score =', f1_score_test)

# recall
recall_train = recall_score(Y_train, X_train_prediction)
print('Training data Recall =', recall_train)
recall_test = recall_score(Y_test, X_test_prediction)
print('Test data Recall =', recall_test)

# precision
precision_train = precision_score(Y_train, X_train_prediction)
print('Training data Precision =', precision_train)
precision_test = precision_score(Y_test, X_test_prediction)
print('Test data Precision =', precision_test)

# accuracy
X_train_prediction = spam_detection_svm.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(training_data_accuracy)
print('Accuracy on Training data : ', round(training_data_accuracy*100, 2), '%')

X_test_prediction = spam_detection_svm.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[525  20]
 [ 57 319]]
Training data F1 Score = 0.8983957219251336
Test data F1 Score = 0.848404255319149
Training data Recall = 0.8768267223382046
Test data Recall = 0.848404255319149
Training data Precision = 0.9210526315789473
Test data Precision = 0.9410029498525073
0.9225543478260869
Accuracy on Training data :  92.26 %
0.9163952225841476
Accuracy on Test data :  91.64 %
